### ISSUE TITLE
Error when using "Comment" field with "Choice" in Step Function

### ISSUE THREAD

**Issue by oscaretu** [aws/aws-toolkit-vscode#1165]
**Describe the bug**

If you use a "Comment" field in a Step Function, VSCode marks it as a erroneus option, and it doesn't draw the graph flow.

**To Reproduce**

In a Step Function, put a "Comment"  field in a element of "Choices" for `"Type": "Choice"`:
 
```
...
		  "NotificationChoice": {
			  "Type": "Choice",
			  "Choices": [
				{
					"Comment" : "Indicates that either Apple customer support canceled the subscription or the user upgraded their subscription",	
					"Variable": "$.lambdaresult.notification_type",
					"StringEquals": "CANCEL",
					"Next" : "Cancel"
				},
...
```

**Expected behavior**

The same code in AWS works without  complain.

**Screenshots**

The editor marks the "Comment" as invalid field
![imagen](https://user-images.githubusercontent.com/2979926/85262345-ef73cc80-b46d-11ea-8569-46e8eadc17cd.png)

And the output window, too:

![imagen](https://user-images.githubusercontent.com/2979926/85262888-ae2fec80-b46e-11ea-8e48-4f4c22cc8e24.png)

**Desktop (please complete the following information):**

-   OS: Windows_NT x64 10.0.18363 (using in from WSL)
-   Visual Studio Code Version:1.45.1 (system setup)
-   AWS Toolkit Version: 1.10.0

**Additional context**

**Comment by vaib-amz** [comment]
Thanks for reporting this issue. I was able to reproduce this issue in the AWS Toolkit for VS Code. The `Choice` state fails validation in the AWS Toolkit when using a `Comment` field for a Choice Rule. This issue is related to the Amazon States Language service, so I have opened a related issue for the repository: https://github.com/aws/amazon-states-language-service/issues/31

**Comment by justinmk3** [comment]
AWS Toolkit 1.11.0 has been released, which fixes this issue.
