### ISSUE TITLE
toolkit was not support AWS China Region

### ISSUE THREAD

**Issue by cydirac** [aws/aws-toolkit-vscode#1246]
Hello my friend,

The plugin cannot based connect to AWS China Region, would you please fix this issue?

Thanks,
Dirac

**Comment by awschristou** [comment]
Hi @cydirac , in order to use the China regions, the toolkit needs to understand which group of regions (aka partition) your credentials relate to. This can be accomplished by defining a region in your shared credentials profile. See [Partition support using Shared Credentials Profiles](https://github.com/aws/aws-toolkit-vscode/blob/master/docs/connecting-to-aws.md#partition-support-using-shared-credentials-profiles).

Here is an example:
```
[some_cn_profile]
aws_access_key_id = SOME_KEY
aws_secret_access_key = SOME_ACCESS_KEY
region = cn-northwest-1
```
