### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by sgalla1** [aws/aws-toolkit-vscode#1355]
**Is your feature request related to a problem? Please describe.**
Users of VSCodium cannot access this extension through the open-vsx marketplace

**Describe the solution you'd like**

Publishing to Open-VSX in additon to VSCode Marketplace would solve this. The process is documented at [Open-VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Describe alternatives you've considered**

Current workaround is to install by the vsix file, but this is manual and doesn't provide auto update

**Additional context**

Motivation for Open-VSX can be found [here](https://www.gitpod.io/blog/open-vsx/)

**Comment by AbhimanyuAryan** [comment]
it's on open-vsx now. Thanks

**Comment by justinmk3** [comment]
Nice, thanks for mentioning that! 

Looks like it is [managed](https://github.com/open-vsx/publish-extensions/blob/660d942a8ca6fc6f1b5d97270ca1306e23445b45/extensions.json#L48-L50) by open vsx, [since 2020, using our published VSIX files](https://github.com/open-vsx/publish-extensions/pull/230#discussion_r529365701).

That seems fine to me. That also means that our [published hash](https://github.com/aws/aws-toolkit-vscode/releases/download/v1.68.0/aws-toolkit-vscode-1.68.0.vsix.sha384) can be used to validate the vsix from open vsx.
