### ISSUE TITLE
Turn off SAM CodeLenses

### ISSUE THREAD

**Issue by BjMrq** [aws/aws-toolkit-vscode#1374]
**Desktop (please complete the following information):**

-   OS: Linux Ubuntu 20
-   VS Code version: 1.50.1
-   AWS Toolkit extension version: 1.15.0

**Question**

Hi, how to turn off the "Add Debug Configuration" that appears before every "exports" in my js files?

I am not using SAM so it makes it a bit annoying.

Thanks for your help.

![Screenshot from 2020-11-02 16-19-16](https://user-images.githubusercontent.com/44323490/97920242-2cf33b00-1d27-11eb-8b3a-cad07bb8efb2.png)

**Comment by justinmk3** [comment]
Currently not supported, good idea though!

**Comment by tzaffi** [comment]
A "bit annoying" is very much an understatement.

**Comment by justinmk3** [comment]
These Codelenses only appear on Lambda handlers, which are a small part of the total lines of code in an application. E.g. for a "hello world" Lambda, there would be 1 codelens in an application with 100s of lines of code. Doesn't seem like a strong reason to introduce a new configuration option. Am I missing something?

If the codelenses are appearing on non-Lambda handler code, would be helpful to have sample cases. Thanks!

**Comment by BjMrq** [comment]
Hello, "only appear on Lambda handlers"
that is the thing they appear not only in Lamda handler but everywhere here are 2 examples, a Knex migration and a middleware in Koa. Sorry if my first post was not clear enough.

![Screenshot from 2020-12-02 12-57-22](https://user-images.githubusercontent.com/44323490/100912066-064b3000-349e-11eb-976f-5c1f1299c9b8.png)
![Screenshot from 2020-12-02 12-56-50](https://user-images.githubusercontent.com/44323490/100912077-08ad8a00-349e-11eb-8793-271c8817bcea.png)

**Comment by justinmk3** [comment]
So the root problem is that the Toolkit's heuristic for deciding what is a Lambda function is pretty loose. In theory, any exported function with 1-3 arguments could potentially be invoked as a Lambda. (We can't use template.yaml to decide, because we support "direct" (no template.yaml) local Lambda run/debug.)

Some ideas...

- More-restrictive heuristic: first arg must be named `event`: `exports.foo = async(event, ...)`
- New command: `AWS: Add Debug Configuration` looks for an exported function (using loose heuristic) at or above the cursor in the current document. So you can still create a debug config from code, even if the codelens (using strict heuristic) does not appear.
- Instead of a codelens, expose `Add Debug Configuration` as a custom [code action / refactoring](https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings).
    - Is this supported by VSCode API?
    - Related: https://github.com/microsoft/vscode/issues/85682

**Comment by bryceitoc9** [comment]
We could also consider turning the CodeLens into a gutter icon (with the actions presented in a hover window). Would you consider that less intrusive?

**Comment by bryceitoc9** [comment]
Agreed, the difficult part is that we put it over anything that can _potentially_ be run as a Lambda function (since that can then be run in isolation by the SAM CLI). The idea behind it was that it would make it super obvious to a user who wants to create a new Lambda function on how to test it with the least bit of fuss.

The latest version of the toolkit does add additional functionality to the codelens if we're able to link it to a function in a `template.yaml` (specifically, letting a user create a new debug configuration based on the template instead of the function in isolation); would you be interested in a mode where we only show codelenses for functions that have this linkage?

**Comment by BjMrq** [comment]
Yes, I guess it would make a lot of sense!

**Comment by tedivm** [comment]
This is extremely obnoxious- it's not only adding this "Add Debug Configuration" line above literally every function, it's also ignoring it when I do configure it- and there should be a simple way to turn it off.

**Comment by Maxoos** [comment]
Ideally this should be a right click context menu item. You can't just assume everyone who has the AWS toolkit uses 95% lambda functions.

**Comment by justinmk3** [comment]
Thanks for the comments. Consider adding your upvote 👍  to the main description so it will be counted when comparing requests in this project.

**Comment by mrtj** [comment]
I'd say _extremly_ annoying, especially because it is implemented buggy.
<img width="198" alt="Screenshot 2021-04-23 at 12 36 00" src="https://user-images.githubusercontent.com/3469711/115859608-b52ddf80-a430-11eb-9e78-d9e8327f8028.png">

**Comment by justinmk3** [comment]
@mrtj see https://github.com/aws/aws-toolkit-vscode/issues/1585 , if you have a way to reproduce that it will help greatly!

Regarding this issue: we are working on this now.

**Comment by bryceitoc9** [comment]
Codelens toggle (also with a command to run the codelens action without clicking a codelens) here: https://github.com/aws/aws-toolkit-vscode/pull/1681 ; feel free to give it a shot (download the artifact from the details of one of the finished packaging tests).

**Comment by justinmk3** [comment]
Toolkit 1.25 adds these features:

- `AWS: Toggle SAM hints` command to show/hide the "Add Debug Configuration" codelenses
- `aws.sam.enableCodeLenses` setting
- `AWS: Add Debug Configuration` which allows you to choose a handler from a menu (instead of inline codelens)

**Comment by ambigus9** [comment]
@justinmk3 Thanks. How to enable this feature: `AWS: Toggle SAM hints command to show/hide the "Add Debug Configuration" codelenses` in AWS Toolkit in Settings of VSCode? I can't find any docs about how to do this. Thanks.

**Comment by justinmk3** [comment]
@ambigus9 open the vscode command menu using ctrl-shift-p (cmd-shift-p on macOS) and type "aws toggle".

**Comment by ambigus9** [comment]
@justinmk3 Thanks! Works perfectly!

**Comment by gregalia** [comment]
Thanks—just what I needed!
