### ISSUE TITLE
Support Environment Variable based AWS Credential

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#164]
If an AWS Credential is set in environment variables, it should be possible to select this from the "Connect to AWS" Credentials selection list.

**Comment by chitsaou** [comment]
This might be helpful for users who manage their credentials with [`aws-vault`](https://github.com/99designs/aws-vault). I don't have a hard-coded credential set in `~/.aws/credentials` so I couldn't use AWS Toolkit for VSCode currently.

**Comment by woodhull** [comment]
I'm not able to use this product since we enforce MFA on AWS using `aws-vault` and roles to control access to AWS from laptops in our organization. Not sure that it's possible to use this tool while also following AWS security best practices re: short lived credentials and MFA.

**Comment by awschristou** [comment]
Manually setting environment variables prior to launching VS Code does not make for a good experience.

If short-term credentials are placed into environment variables, this would require users to close VS Code, re-assign the environment variables, and then re-launch VS Code every time the credentials expire. This too does not make for a good experience.

If the short-term credentials are set to expire on a longer interval which aligns with how long a user would be in VS Code, this runs counter to the best practice of "short-term" credentials.

We're currently inclined to close this feature for these reasons.

I'm not familiar with aws-vault, but it [appears to have support for `credential_process`](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential-helper), which is something the toolkit added support for more recently. @woodhull or @chitsaou would you be able to see if this is able to suit your needs?

**Comment by woodhull** [comment]
I was able to get this working!

One point of confusion for me was the AWS VS Code plugin looking for `~/.aws/credentials` while `aws-vault docs refer to `~/.aws/config`. 

I was getting a file not found error for the credentials file from AWS VS Code plugin. I fixed this by copying the contents of `config` into `credentials` since I wasn't sure what the right thing to do was. 

Regardless, more docs and in-app help here would be useful. Many people are not familiar with all of the intricacies of AWS auth and how the CLI works. 

I agree that `credential_process` feels like a good mechanism but only if people can realize how to use it correctly. For me at least I'm not clear on what should go in the config file vs. the credentials file.

**Comment by awschristou** [comment]
Thanks for the info @woodhull ! The situation you encountered where an error occurs when a `config` file is present but a `credentials` file is absent is a separate issue in #641

**Comment by edwdev** [comment]
We use an external tool to assume appropriate roles and set the necessary environment variables, used for AWS access. AWS cli commands work as they should, but after setting the variables and opening Vscode, it still seems like Vscode is not picking up these, and instead constantly wants to use a name profile in the credentials file. Any ideas on this ?

**Comment by justinmk3** [comment]
@edwdev does an "env" item appear in the `AWS: Choose AWS Profile...` menu? You can also reach that same menu via the "AWS" statusbar item:

![image](https://user-images.githubusercontent.com/55561878/185717052-a9ddb440-17c6-4d67-986f-4b70738bab6e.png)

If there is no "env" item in the menu this means AWS Toolkit didn't see the expected `AWS_*` environment variables. There should be some info in the Toolkit logs indicating why. 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.

**Comment by Leigh-M** [comment]
IMHO it's a terrible user experience having to input your MFA credentials sometime 8-12 times per day when the creds expire. How much lost time per sprint/ year? Say it takes 4 mins of breaking concentration that's 45 mins per day on my MFA device! 

VSCode needs AWS-vault support (or any other tool to manage the MFA temp creds expiry for you, but AWS-vault is the industry standard already)

**Comment by jordyjwilliams** [comment]
I was experiencing similar issues to this due to use of `aws-vault` and the VS code extension, thanks for this solution and discussion. Using the [credential process](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process) in `~/.aws/config` enabled me to get this working as expected!
