### ISSUE TITLE
Update Toolkit with changes to credentials file

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#168]
The credentials file should have a watch on it, and when it changes:

* if the currently active profile is detected to have changed, the toolkit should reconnect with the updated profile
* if any cached profile entries are detected to have changed, those cached entries should be evicted
* ensure that any validation steps (i.e. `getCallerIdentity`) are performed on each change.

Note: Keep telemetry in mind when making this change--subsequent metrics should include the new account id, not the old id.

**Comment by bryceitoc9** [comment]
A separate realization from https://github.com/aws/aws-toolkit-vscode/pull/554 (caching account ID) is that we aren't detecting manual changes to the credentials. Since we only need to check the credentials file when we're checking the account ID, a first crack at this issue can be checking the file's last modified date, similar to what we're doing with the SAM CLI.

https://github.com/aws/aws-toolkit-vscode/pull/555 is currently modifying the existing SAM CLI caching code; let's revisit this once these two PRs are merged.

**Comment by mpiroc** [comment]
Keep telemetry in mind when making this change--subsequent metrics should include the new account id, not the old id.

**Comment by awschristou** [comment]
At this time, the toolkit will not put a watch on the shared credentials files.
Instead, each time the credentials list is shown, and each time credentials are selected for connecting to AWS, the most recent version of the profiles will be used from the shared credentials files.  This change is under review in #888

**Comment by awschristou** [comment]
Version 1.6.0 of the Toolkit is now released, with the functionality mentioned in https://github.com/aws/aws-toolkit-vscode/issues/168#issuecomment-572291001
