### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-toolkit-vscode#178]
Further explanation and screenshots would be great, so people understand exactly what this extension does before investing the time to clone & build it manually.

**Comment by bryceitoc9** [comment]
We've added the following since our last release:
* Some images to [`README.md`](https://github.com/aws/aws-toolkit-vscode/blob/master/README.md) for help with configuring a user-built version
* A second readme page ([`extension-readme.md`](https://github.com/aws/aws-toolkit-vscode/blob/master/extension-readme.md)) which is used as the VS Code Marketplace page (this is mainly focused around using the plugin instead of building it)
* The full AWS documentation page: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/welcome.html

Is there any additional information you're looking for us to document?

**Comment by mpiroc** [comment]
Closing as most of the README content has been moved to the user guide, which contains plenty of screenshots. Feel free to re-open if you feel that something is missing.
