### ISSUE TITLE
Excessive `rg` process usage

### ISSUE THREAD

**Issue by dnicolson** [aws/aws-toolkit-vscode#2327]
**Describe the bug**
Enabling the AWS Toolkit extension results in the `rg` process spiking to over 1000% CPU utilization when running an extension, for example, the [Cat Customs - Custom Editor API Samples](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample) extension.

**To Reproduce**
1. Enable AWS Toolkit extension
2. Clone [Cat Customs - Custom Editor API Samples](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample) extension
3. Click "Run Extension"

VS Code 1.62.3
macOS 11.6 (20G165)
AWS Toolkit 1.33.0

**Expected behavior**
No excessive CPU utilization.

**Additional context**
The issue may be related to activation events.

**Comment by justinmk3** [comment]
related: https://github.com/aws/aws-toolkit-vscode/issues/1248

**Comment by JadenSimon** [comment]
VS Code is in the process of migrating to a new file watcher so I'm wondering if that could be causing problems. Could you try running the extension on Insiders and see if you have the same issue? I was not seeing any `rg` process spikes on my Mac using the same steps so it may be something with your local environment.

**Comment by dnicolson** [comment]
The issue doesn't appear to exist with version 1.63.0-insider. It's not clear if the underlying cause of the issue is resolved though.

**Comment by JadenSimon** [comment]
I'm thinking the high `rg` CPU usage is a VS Code issue combined with the toolkit's heavy usage of `findFiles` for CodeLenses. We also activate the extension shortly after start-up due to https://github.com/aws/aws-toolkit-vscode/pull/1195 which is not ideal.

Some ideas to help toolkit performance:
* Scope down the activation events to something more reasonable
* Give up searching for files after X seconds (maybe 30?)
* Add exclude patterns for things like `node_modules` by default
* Use `max_results` when possible
* Make only a single `findFiles` call instead of one for each language

Some additional investigation is definitely warranted.

**Comment by justinmk3** [comment]
AWS Toolkit 1.73 (next release) will include https://github.com/aws/aws-toolkit-vscode/pull/3445 which improves performance if the `aws.samcli.enableCodeLenses` setting is disabled.
