### ISSUE TITLE
Delete command not found

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#242]
**Describe the bug**

**To Reproduce**
<img width="655" alt="screen shot 2019-02-07 at 3 12 06 pm" src="https://user-images.githubusercontent.com/8992246/52449073-d4a7ee80-2aea-11e9-8265-b96fa60c44b1.png">
<img width="513" alt="screen shot 2019-02-07 at 3 12 16 pm" src="https://user-images.githubusercontent.com/8992246/52449076-d70a4880-2aea-11e9-9084-956b8a3b68c3.png">

**Comment by awschristou** [comment]
The command is registered to a context menu, and isn't intended to be exposed through the command palette. When the command is not found, it is because the extension is not loaded yet. In most cases, even if the extension is loaded, the command would not work properly. The fix is now in the `develop` branch, removing the command from the context menu.
