### ISSUE TITLE
Get Configuration command from command pallet shows can't connect to AWS

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#245]
**Describe the bug**
The AWS: Get Configuration command errors out when invoked from command palette
**To Reproduce**
1. Run `AWS: Get Policy` from palette
2. Get notification it can't connect to AWS, even though the explorer works

**Comment by awschristou** [comment]
The command is registered to a context menu, and isn't intended to be exposed through the command palette. When the command is not found, it is because the extension is not loaded yet. In most cases, even if the extension is loaded, the command would not work properly. The fix is now in the `develop` branch, removing the command from the context menu.
