### ISSUE TITLE
Get Policy always fails when invoked from palette

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#246]
**Describe the bug**
The `AWS: Get Policy` command always fails when invoked from palette

**To Reproduce**
1. Run `AWS: Get Policy` from palette
2. Get errors `Cant connect to AWS` and `No lambda found`

3. Select a Lambda in explorer
4. Run command from palette
5. Get same errors

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Visual Studio Code Version:
 - AWS Toolkit for Visual Studio Code Version:

**Additional context**

**Comment by awschristou** [comment]
The command is registered to a context menu, and isn't intended to be exposed through the command palette. When the command is not found, it is because the extension is not loaded yet. In most cases, even if the extension is loaded, the command would not work properly. The fix is now in the `develop` branch, removing the command from the context menu.
