### ISSUE TITLE
Cannot see VPC and network resources in the explorer

### ISSUE THREAD

**Issue by iona-on** [aws/aws-toolkit-vscode#2557]
**Describe the bug**
I can't see any of my VPCs in the explorer. I have tried with multiple regions

1. Set up Explorer with credentials
2. Navigate to List of Resources
3. Try to find deployed VPCs

**Expected behavior**

List of VPCs deployed and networking resources will be present 

**Desktop (please complete the following information):**

OS:  Darwin arm64 21.2.0
Visual Studio Code Extension Host Version:  1.65.2
AWS Toolkit Version:  1.37.0

**Comment by justinmk3** [comment]
Thanks for your request. Although AWS Toolkit currently doesn't have full support for EC2 or VPCs, we provide a generic `Resources` list driven by [AWS Cloud Control](https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/) which lists all resources returned by Cloud Control.

Check the `Resources` node in AWS Explorer to see all such items. Because the list is large, you can configure which resources to show/hide by clicking the icon or using the context menu on `Resources`.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/55561878/161095600-0b90b45f-2cd7-48d7-bf5e-eb850a841996.png">


Further integration with EC2 VPCs is tracked in #1560.
