### ISSUE TITLE
 Inaccessible host: `sts.eu-west-1.amazonaws.com' at port `undefined'.

### ISSUE THREAD

**Issue by slamer59** [aws/aws-toolkit-vscode#2689]
## Problem
I cannot Connect to AWS

## Steps to reproduce the issue

Click **Connect to AWS button** 
Choose the profile

Get this error:
`2022-06-09 14:45:42 [ERROR]: Error getting AccountId: [UnknownEndpoint: Inaccessible host: `sts.eu-west-1.amazonaws.com' at port `undefined'. This service may not be available in the `eu-west-1' region.`

You can see the port unknown.
 
config 
```
[default]
region = eu-west-1
ca_bundle = C:/***.crt

[profile my@email.com]
region = eu-west-1
role_arn = arn:aws:iam::XXXXXXXX:%%%%%%%%%%%%%
output = json

[profile profileX]
region = eu-west-1
role_arn = arn:aws:iam::YYYYYYYYYYYYYY:**************
source_profile = my@email.com
```

Credential 
```
[my@email.com]
aws_default_region = eu-west-1
aws_access_key_id = <>
aws_secret_access_key = <>
aws_session_token = <>
```

It works with the CLI.

## System details (run the `AWS: About Toolkit` command)

-   OS: W10
-   Visual Studio Code version: 1.67.2
-   AWS Toolkit version:  v1.39.0

**Comment by JadenSimon** [comment]
Does this happen consistently? I've seen multiple issues on the AWS SDK repository for the same thing (example: https://github.com/aws/aws-sdk-js/issues/4079).

Older issues seem to imply that this is due to transient network failures, though if this happens every single time then it could be due to a networking configuration. The error is emitted [here](https://github.com/aws/aws-sdk-js/blob/66ac72f2bb52fc714f736c111d012a9002670433/lib/event_listeners.js#L543-L554) and is thrown on DNS failures.

**Comment by slamer59** [comment]
Hello, yes it is consistently happening and the CLI is working "at the same time". 

I am behind a proxy. I wonder if it can be realted to this.

**Comment by justinmk3** [comment]
Proxy support is a known limitation: https://github.com/aws/aws-toolkit-vscode/issues/185
