### ISSUE TITLE
SAM json schema: cannot change schema in template.yaml file

### ISSUE THREAD

**Issue by justinmk3** [aws/aws-toolkit-vscode#3012]
## Problem

Cannot manually select a  different json schema in SAM template.yaml. 

## Steps to reproduce the issue

1. Choose a different schema from the status bar:
    - ![image](https://user-images.githubusercontent.com/55561878/204043965-8563ba13-081e-44cd-b8b0-4641194dbaeb.png)
2. the schema is ignored and the selection remains `aws://sam.schema.json`

## System details (run the `AWS: About Toolkit` command)

-   OS:
-   Visual Studio Code version:
-   AWS Toolkit version:

**Comment by jpinkney-aws** [comment]
I just looked through a bit of the code, unfortunately it’s technically not possible to do this because the VSCode YAML extension API takes precedence over schemas that are provided through the modelline/the vscode settings

**Comment by hoffa** [comment]
> I just looked through a bit of the code, unfortunately it’s technically not possible to do this because the VSCode YAML extension API takes precedence over schemas that are provided through the modelline/the vscode settings

Can you clarify what the technical challenge is making it impossible?

**Comment by jpinkney-aws** [comment]
The way the VSCode-YAML API works is, given an intellisense action (hover, validation, completion, etc), it will query all the extensions that are currently registered to use it's API and then ask them if this file is supported by their extension.

E.g. In our case, we see a SAM file in VSCode so we tell VSCode-YAML that we are the ones who should be providing the schema for this file.

Once VSCode-YAML see's that an extension is ready and available to send a schema for the given file, it disables all other modes of settings the schema (modeline, `yaml.schemas`, etc) for that file.

This is by design, since theoretically an extension should be able to recognize their files and then provide support for them, that way users don't have to manually specify schemas using the modeline or the `yaml.schemas` setting.

The problem here is we aren't able to easily override the way the VSCode-YAML API works. So right now, the VSCode-YAML API sees that our extension will send back the schema for the given SAM file and then disables all other ways to set the schema

**Comment by jpinkney-aws** [comment]
It's not necessarily impossible, but the approach I had to take in https://github.com/aws/aws-toolkit-vscode/pull/3013 is definitely not an ideal one, since on every SAM intellisense request you need to read in the file, check if it has a modelline and then if it does, error out so that VSCode-YAML won't continue to use the registerContributor API for that request

**Comment by hoffa** [comment]
For context, this is affecting https://github.com/aws/serverless-application-model/discussions/2645

**Comment by justinmk3** [comment]
Documentation: https://github.com/redhat-developer/yaml-language-server#using-inlined-schema

after AWS Toolkit updates to  vscode-yaml version 1.11+, AWS Toolkit users can add a  `yaml-language-server` "modeline" to the top of a YAML file to force the use of a schema by URI:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/aws/serverless-application-model/main/samtranslator/schema/schema.json
```

**Comment by justinmk3** [comment]
This should now be possible. To try it out, ensure that you have updated the [vscode yaml extension](https://github.com/redhat-developer/vscode-yaml) to the latest version.
