### ISSUE TITLE
Hover getting disabled automatically by AWS Tookit

### ISSUE THREAD

**Issue by aproli90** [aws/aws-toolkit-vscode#3014]
## Problem
Since few days, the hover popup in my VSCode gets disabled automatically for the current user. Basically, the property @id:editor.hover.enabled is unset for User, but remains checked for Workspace

## Steps to reproduce the issue
I have not been able to pinpoint what triggers this issue, but know the code that's causing it.

Refer this VSCode github issue to understand the exact issue: https://github.com/microsoft/vscode/issues/165988

The root cause was identified by one of their Principal Software Engineering Managers ([Alexandru Dima](https://github.com/alexdima)): https://github.com/aws/aws-toolkit-vscode/blob/6b8d0d63b9481e4a61708e47df2dd44d89e268ee/src/codewhisperer/util/hoverConfigUtil.ts#L9-L37

As per the code, you guys seem to be doing a workaround for inline completions, which is having a bug.

## Expected behavior
The hover functionality should not get auto-disabled

## System details (run the `AWS: About Toolkit` command)

OS: Windows_NT x64 10.0.22621
Visual Studio Code extension host:  1.70.0
AWS Toolkit:  1.53.0
node: 16.13.2
electron: 18.3.5

**Comment by justinmk3** [comment]
Thanks for reporting this! Could be related to https://github.com/aws/aws-toolkit-vscode/commit/a535688f6a472695b7778c6b2cf535899b78e316 , however that change was included as far back as AWS Toolkit 1.51. If the issue only started a few days ago, it will help to narrow down the version where it was introduced. 

You mentioned that you are using AWS Toolkit 1.53.0. The latest version is 1.56, which includes many CodeWhisperer improvements. Can you try 1.56? If the issue still persists there, in vscode you can `Install Another Version` of AWS Toolkit as shown below.  Does the issue happen in 1.52 / 1.51 / 1.50?
 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/55561878/204335491-aad3b989-dc6a-4bdb-ab87-deab0aa05f7e.png">

**Comment by aproli90** [comment]
I have been observing this issue for at least 1.5 months now. Also, the suspected file doesn't have any commit after Sept 22 ([file history](https://github.com/aws/aws-toolkit-vscode/commits/a535688f6a472695b7778c6b2cf535899b78e316/src/codewhisperer/util/hoverConfigUtil.ts)). So, I doubt the latest version has this fixed. But I still upgraded to 1.56. Will let me know if it's still persistent.

If it does, will try your suggestion of downgrading too. It might be a very slow process to debug though since I don't know what exactly triggers this issue

**Comment by justinmk3** [comment]
@aproli90 we have confirmed this issue and we are working on a fix.

**Comment by hediet** [comment]
> workaround for inline completions, which is having a bug.

If there is a bug indeed, we would appreciate if you could file an issue in the VS Code repo!

**Comment by aproli90** [comment]
> > workaround for inline completions, which is having a bug.
> 
> If there is a bug indeed, we would appreciate if you could file an issue in the VS Code repo!

I don't have details on why it's a workaround for a bug. I just suspect it. All I see if hover being disabled forcefully in toolkit extension at the given line number. Would be great if one of the engineers from your team who have the context file the issue

**Comment by justinmk3** [comment]
Sharing an update on this AWS Toolkit issue (see also https://github.com/aws/aws-toolkit-vscode/issues/3014 ):

AWS Toolkit provides suggestions from [CodeWhisperer](https://aws.amazon.com/codewhisperer/). To do so, we implement [vscode.InlineCompletionItemProvider](https://github.com/aws/aws-toolkit-vscode/blob/c146b6e8edb92396d21746efdd03351c2c47475c/src/codewhisperer/service/inlineCompletionService.ts#L142). We also [override "editor.action.inlinesuggest.shownext"](https://github.com/aws/aws-toolkit-vscode/blob/c146b6e8edb92396d21746efdd03351c2c47475c/src/codewhisperer/service/inlineCompletionService.ts#L179-L191)  and related commands _when CodeWhisperer is providing suggestions_ so that the inline suggestion popup `Next` and `Previous` buttons provide CodeWhisperer suggestions.

- Waiting for advice from Microsoft: https://github.com/microsoft/vscode/issues/165988#issuecomment-1349679114

As a short-term solution, we've removed the workaround in AWS Toolkit v1.59 (not released yet) that temporarily disabled the hover popup. But now on mouse-hover, users that have installed GitHub Copilot will see a popup with a `Open GitHub Copilot` button (while CodeWhisperer is providing suggestions), which is very confusing.


![image](https://user-images.githubusercontent.com/55561878/207440901-e2e5df04-b617-41f2-b237-0f488b37849e.png)

**Comment by justinmk3** [comment]
This should be fixed with AWS Toolkit 1.60. Sorry for the trouble!
