### ISSUE TITLE
filter cloudwatch log groups

### ISSUE THREAD

**Issue by scanianick** [aws/aws-toolkit-vscode#3087]
## Problem
We have a lot of log groups and it is very hard to find the groups you are looking for. Would be great to have a filter function.
## Expected behavior
To have a filter function

**Comment by justinmk3** [comment]
The upcoming `Search Log Group` command https://github.com/aws/aws-toolkit-vscode/pull/3570 will help with this a bit since it allows using the vscode quickpick menu to select a Log Group.

The more general idea of being able to sort/favorite/manage items in AWS Explorer is tracked in these issues:
https://github.com/aws/aws-toolkit-vscode/labels/search-filter-tag

**Comment by justinmk3** [comment]
Tracked in https://github.com/aws/aws-toolkit-vscode/issues/1398
