### ISSUE TITLE
Security Scan Job Timeout

### ISSUE THREAD

**Issue by mdlafleur** [aws/aws-toolkit-vscode#3374]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows_NT x64 10.0.19042
-   Visual Studio Code version: 1.76.0
-   AWS Toolkit version: 1.70.0

## Question
Connected with AWS Builder ID
Run Security Scan gives me the following:
Security scan failed.  Error: Scan job timeout.

How to resolve?

**Comment by leigaol** [comment]
Hi @mdlafleur ,  could you upgrade to the latest 1.80.0 AWS Toolkit for VS Code and try again? 

You can test security scan feature with a smaller Java project to begin with. A larger Java project takes more time to scan, which may result in a time out if it cannot be completed in one minute. Meanwhile, to scan a java project, it has to be compiled otherwise you should see a "Try rebuilding the Java project or specify compilation output in Settings" warning at the lower right corner.

If upgrading does not resolve your issue, feel free to send me the error logs of your AWS Toolkit when performing the security scan. 

Thanks.

**Comment by mdlafleur** [comment]
@leigaol It worked after upgrade.
