### ISSUE TITLE
InvalidGrantException: UnknownError

### ISSUE THREAD

**Issue by spencerthayer** [aws/aws-toolkit-vscode#3394]
I beleive @justinmk3 prematurely closed issue #3064.

I too am unable to sign in.
![image](https://user-images.githubusercontent.com/1019815/234938948-780d0a55-675f-4bff-a89b-ed761116df80.png)

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-vscode/issues/3064 is still open. It's locked to prevent further comments, so that the latest information is easier to find.

If you're running into a different issue then opening a new issue is preferred. But this doesn't sound like a different issue, so this is a duplicate?

**Comment by justinmk3** [comment]
The screenshot shows `Select IAM Credential`. If you click that, what happens?

**Comment by justinmk3** [comment]
Based on your comment https://github.com/aws/aws-toolkit-vscode/issues/3329#issuecomment-1526051928 I think I understand the issue. Pasting my reply from there:

> `Select IAM Credentials to View Resources` is for AWS Explorer, not CodeWhisperer.
>
> CodeWhisperer sign-in is available in the `Developer Tools` panel. If you don't see that panel, right-click on vscode to enable it: 
> <img width="464" alt="image" src="https://user-images.githubusercontent.com/55561878/234943589-af61459f-c194-497c-ab6c-1c939182ec7b.png">

If you are still have issues let us know.
