### ISSUE TITLE
use-container support for local run/debug of lambda functions

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#370]
This allows users to locally run / debug lambda functions that have native package references.

Acceptance Criteria:
* Each handler configuration has an optional `useContainer` boolean
* if the value is missing, it is treated as false
* when functions are locally run/debugged, the handler config drives usage of the `--use-container` arg when running sam cli
* autocompletion support for the field provides a description, and mentions false as the recommended/default value (if #369 is not delivered yet, break this into a separate task)

**Comment by mpiroc** [comment]
`--use-container` is not supported when building .NET Core apps, so we should warn if the user tries to set it for a .NET Core lambda.

**Comment by jpangburn** [comment]
Right now I'm using the command line and remote debugger to debug because I need a container build, so this feature supporting that would be nice.  I think this feature will become more important as people move beyond hello world and start trying to do stuff that requires more modules.  Using the command line is ok, but this would really speed up the debug iteration time on more complicated projects.

**Comment by awschristou** [comment]
Hi @jpangburn , I've created a branch that prototypes use container support when building sam applications for local debugging. If you're able to build the toolkit from this repo, and are interested in trying it out, the branch is `awschristou/prototype-use-container`. I'd be interested in hearing if this works for you.  To use it, you'd click the "Configure" CodeLens, and then add a `useContainer` boolean field to your lambda handler's configuration, setting it to true.

**Comment by jpangburn** [comment]
Hi @awschristou , I haven't used a development version of a vscode extension before, so please forgive any extra detail provided here.  The short story is it didn't seem to work on my mac, the build seems to hang.

When I click the "Debug Locally" link, I get the following and it hangs:

> Preparing to run app.lambda_handler locally...
Building SAM Application...

I switched to the "AWS Toolkit Logs" output window to see what it's doing.  It showed the command it was trying to run, so I tried it at the command line:

> jpangburn$ /usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkS0txmP/output --template /tmp/aws-toolkit-vscode/vsctkS0txmP/input/input-template.yaml --base-dir /Users/jpangburn/Documents/amazon_aws/aws_sam_projects/personal/sam-app36/hello_world --use-container --manifest /tmp/aws-toolkit-vscode/vsctkS0txmP/debug-requirements.txt
Starting Build inside a container
Building resource 'awsToolkitSamLocalResource'
> 
> Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting /Users/jpangburn/Documents/amazon_aws/aws_sam_projects/personal/sam-app36/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
^C
Aborted!

I hit ^C because it appeared hung.  A container build just at the directory where `template.yaml` resides works just fine:

> jpangburn$ sam build --use-container
Starting Build inside a container
Building resource 'HelloWorldFunction'
> 
> Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting /Users/jpangburn/Documents/amazon_aws/aws_sam_projects/personal/sam-app36/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
> 
> Build Succeeded

So not sure which of the parameters sent by the Debug Locally link vs the command I used caused it to break.  At least we know it sent the `--use-container` switch.

I tried setting the Runtime in template.yaml to Python 3.6 (that's what I have on my machine, setting it to 3.7 is the test I used to have a reason for needing the container build) and set the useContainer flag to false and the Debug Locally worked fine.  I checked the logs again and the command was:

> /usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkZTpCcV/output --template /tmp/aws-toolkit-vscode/vsctkZTpCcV/input/input-template.yaml --base-dir /Users/jpangburn/Documents/amazon_aws/aws_sam_projects/personal/sam-app36/hello_world --manifest /tmp/aws-toolkit-vscode/vsctkZTpCcV/debug-requirements.txt

This worked just fine.  Trying to build with a 3.6 container hangs too in vscode and works fine from the command line.  Not sure what else to try.

**Comment by awschristou** [comment]
Hi @jpangburn , I'm wondering if there is a delay while the docker image used to build the application (eg: `lambci/lambda:build-python3.7`) is being pulled. The toolkit does not surface enough of the command outputs while `sam build` is run, so it is hard to tell if it is frozen, or actively working on something.

After you've successfully run a command involving `--use-container` from the terminal, could you please try the same app/configurations back in the toolkit to see if it proceeds?

**Comment by jpangburn** [comment]
Hi @awschristou , you're talking about the problem where if you debug and it's pulling the image and it times out.  Then if you do it from the command line so the image is cached on your machine, the next time you run from vscode you don't hit the timeout because the image is cached.

Yeah, I thought the same, that's why I ran the same command that vscode was using from the command line in my output above.  The one that ends in `Aborted!`  You can see it downloaded the image and then mounted the project in the container when it hung.

So it looks like it must be in ones of those output files, right?  Like the template, or the modified python with the debugger code, or the manifest, or something.  I thought it must be that one of those wasn't compatible with useContainer or something.  But had no idea where to start looking as I don't know the insides of this thing.

**Comment by justinmk3** [comment]
AWS Toolkit 1.12 (released today) includes the new [SAM local Lambda debugging experience](https://github.com/aws/aws-toolkit-vscode/pull/1215) which leverages VS Code "launch configurations". 

Full documentation: https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/run-debug-sam-app.html

The  `aws-sam` launch configuration supports a `sam.containerBuild` field which internally sets `--use-container`.
