### ISSUE TITLE
Invalid client on Builder ID authentication

### ISSUE THREAD

**Issue by mtsanaissi** [aws/aws-toolkit-vscode#3769]
## System details (run the `AWS: About Toolkit` command)

-   OS: Windows_NT x64 10.0.22621
-   Visual Studio Code version: 1.81.1
-   AWS Toolkit version: 1.85.0

## Question

When trying to authenticate to Code Whisperer, using Builder ID, I am getting "Invalid client provided".
I didn't open this issue as a bug because I am not sure the problem is within the extension or the authentication service.
Funny thing is, this problem occurs when I am using my regular VS Code, but if I am using VS Code with WSL (Ubuntu), the authentication works.

Regular VS Code leads me to https://view.awsapps.com/start/user-consent/authorize.html?clientId=V_etc_&clientType=a_etc_&deviceContextId=Z_etc_&region=us-east-1
WSL VS Code leads me to https://view.awsapps.com/start/user-consent/authorize.html?clientId=b_etc2_&clientType=a_etc_&deviceContextId=Z_etc_&region=us-east-1

Each leads to an auth URL with different clientId.

Tried restarting my pc. Tried opening the authentication URL in an incognito browser session. Tried logging out of all active sessions in AWS. Nothing worked.
(Edit: Also tried reinstalling AWS Toolkit extension)

![image](https://github.com/aws/aws-toolkit-vscode/assets/16047606/dd5aca60-5602-4d65-ab04-284bb7e97dd2)

Hope someone can help me find a solution for this problem! Thanks!

**Comment by justinmk3** [comment]
If you had previously tried to use AWS Builder Id awhile ago (several months), it's possible this is because of stale state. For troubleshooting, try moving or deleting the `~/.aws/sso/` directory (if it exists) in your home directory. Then restart vscode and try again.

If that doesn't work, can you provide the Toolkit logs (check that private info is removed)? 

1. In VSCode settings, ensure that "aws log level" is "debug".
2. Perform the steps to reproduce the issue.
3. Use the `AWS: View Toolkit Logs` command to get the logs.

Related:

- https://github.com/aws/aws-toolkit-vscode/issues/3351
- https://github.com/aws/aws-toolkit-vscode/issues/3667

**Comment by mtsanaissi** [comment]
I deleted my C:\Users\myuser\.aws\sso folder, reinstalled the extension, restared VS Code, and it worked!
I have searched for a similar issue but I forgot to remove the filter is:open.
Thank you @justinmk3!

**Comment by justinmk3** [comment]
AWS Toolkit 1.93 includes a fix for potential "Invalid client" issues. Please let us know if you notice any improvement (or not)!
