### ISSUE TITLE
No longer able to connect after authenticating in terminal with `isengardcli assume`

### ISSUE THREAD

**Issue by austinmw** [aws/aws-toolkit-vscode#4086]
## Steps to reproduce the issue

1. `isengardcli assume`
2. Open Jupyter notebook in VSCode
3. click `AWS: Connect to AWS`
4. In notebook cell: `!aws s3 ls`
5. See authentication error

## Expected behavior

Authenticate properly

## System details (run the `AWS: About Toolkit` command)

-   OS: Mac, latest
-   Visual Studio Code version: Insiders, latest
-   AWS Toolkit version: v1.100.0

**Comment by justinmk3** [comment]
I assume that `isengardcli assume` updates your `[default]` profile, and you are using that via `AWS: Connect to AWS`.

`!aws s3 ls` depends on the `[default]` profile, or else `$AWS_XX` environment variables in its terminal. AWS Toolkit has never provided such environment variables, so my guess is that something else caused this to accidentally work, and now it doesn't.

Since the issue title implies that this used to work, you can try "bisecting" by installing older AWS Toolkit versions and find the exact AWS Toolkit version that introduced the issue (and confirm that the _previous_ version before that one does _not_ have the issue).

**Comment by justinmk3** [comment]
Note that https://github.com/aws/aws-toolkit-vscode/pull/3040 is a related feature we're working on, which adds the ability to "inject" the `$AWS_XX` env vars to a vscode terminal. If you want to [try the PR artifact](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#prerelease-artifacts) we'd love to hear your feedback on it.

**Comment by austinmw** [comment]
Ah, looks like it came from switching from using iTerm2 a few weeks back, and forgetting I had a script named `.iterm2_shell_integration.zsh` from the isengardcli devs that allowed it to work.
