### ISSUE TITLE
Fix line number mappings when debugging Python lambda functions

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#435]
Currently, if I set breakpoints in a python lambda function and start debugging from code lens, the debugger breaks on the wrong lines. We need to determine why this is, and provide appropriate line mappings to fix it.

**Comment by bryceitoc9** [comment]
@mpiroc Do you have any specific examples of code you were trying? I'm messing around with some basic examples, and I can't replicate the error.

**Comment by bryceitoc9** [comment]
Looks like this might be a non-issue. We were only able to replicate this on lines initializing a Python dictionary; in our case, this meant dropping a breakpoint on the Python 3.6 demo app's `return {` line.

If there is any code above it, the breakpoint will move to that line instead.

This also affects local debugging through VSCode for non-SAM applications. Debugging the following code in Python 3.6 with a breakpoint on the first line will completely skip the breakpoint:
```
x = {
    'a': 1
}

print(x)
```
(breaking on lines 2 and 5 work correctly, breaking on lines 3 and 4 bump the breakpoint to line 2)

This does not affect Python 2.7. It does appear that PyCharm on Python version 3.6 also is affected.

Will see if I can find confirmation that this is a language quirk, rather than a SAM/debugger/IDE/toolkit quirk.

**Comment by bryceitoc9** [comment]
It doesn't appear that `pdb` executed through the command line stops on dictionaries either.

**Comment by bryceitoc9** [comment]
Closing as a no-op. Python is as Python does.
