### ISSUE TITLE
Instead of repeatedly attempting to attach the Python debugger, wait until the handler is ready for attach.

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#436]
When a user debugs a python lambda function using one of our codelenses, we:

1. Wait for the relevant port to open on SAM's underlying docker container.
2. Repeatedly attempt to attach the debugger until we succeed or time out.

The has several disadvantages, most importantly:

1. Every time that we attempt and fail to attach, VS Code displays an non-supressable error message which the user must dismiss.
2. Depending on our retry interval, the user may have to wait longer than necessary for the debugger to attach.

Instead, we should wait for the python lambda to print a message indicating that it is ready for the debugger to attach, *then* attempt to attach.

**Comment by bryceitoc9** [comment]
Covered here: https://github.com/aws/aws-toolkit-vscode/pull/440

**Comment by micholas** [comment]
What I learned on Monday, April 25 with this [branch](https://github.com/aws/aws-toolkit-vscode/compare/feature/python-debug...micholas/feature/python-debug) is that `waitForDebugPort` this ensures that `vscode.debug.startDebugging` therefore won't return false and won't show the non-supressable error message. Instead `vscode.debug.startDebugging` returns either `true` if the debugger is attached, otherwise `undefined`. My experimentation showed that the best performance was to eliminate the `onWillAttachDebugger` delay and wait 200ms between retries. For me it consistently connected on the second try (1st retry after only one 200ms delay).

Oddly if I attempted to simply add a 200ms (or even 500 or 1000ms) delay in `onWillAttachDebugger`, the debugger din't attach on the 1st try.

**Comment by awschristou** [comment]
This issue was written up to track work where we call SAM CLI in a child process instead of a vs code task, so we can capture and process the output. For now, we've taken the approach outlined in the issue. We had a misunderstanding that we were getting debugger attach failures despite waiting for the port to be open, which wasn't the case.

Closing this task. If we pursue the child process approach in the future, we will create an issue at that time.
