### ISSUE TITLE
Add help links to the Credentials related dialogs/wizards

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#531]
All aspects of the existing Credentials experience need to be checked. It should be possible to get guidance or assistance from any portion of the user flows (whether they are wizards or dialogs)

Situations include but are not limited to:
* Creating a new credential on a system with no shared credentials file (adding valid and invalid credentials)
* Entering MFA tokens (correctly and incorrectly)

First step: Create a list of the places in which we need to provide additional guidance, and describe how we should provide guidance for each.

Look at JetBrains toolkit for reference.

**Comment by mpiroc** [comment]
Obtain permalinks instead of linking directly to the docs.

**Comment by cnicklin** [comment]
bumping this issue: I'm trying to do initial setup. I can't figure out how to add my credentials. I start following the wizard, which asks for Access Key and Secret Access Key but doesn't ask for my Session Token. I think I need to set up SSO credentials but the only documentation I can find tells you to [edit the credentials file](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/sso-credentials.html), which doesn't exist yet because the wizard keeps failing. How do I create a credentials file without the wizard?

**Comment by JadenSimon** [comment]
Hi @cnicklin ,

We unfortunately haven't gotten around to setting up a wizard for different types of credentials (SSO/MFA/etc.), but this is something we are actively working towards. Looks like we also made some changes to the wizard flow to validate credentials before proceeding, whereas before it would just create a stub file. If you already have the AWS CLI installed, the fastest and easiest way to get SSO credentials set-up would be to run:
```
aws configure sso
```
This will prompt you for some parameters, then configure the the credentials file automatically. Otherwise, you will instead need to manually create a file with the following path:
```
~/.aws/credentials
``` 
For Windows this is `%USERPROFILE%/.aws/credentials`. Now the wizard will take you directly to an empty file. Add the following (with your own information) to set-up a profile for SSO:
```
[default]
# the SSO entry-point URL
sso_start_url = https://my-sso-portal.awsapps.com/start 

# which region to use to sign-in (this is different from which region to run commands in)
sso_region = us-west-2 

# the account ID to sign into
sso_account_id = 123456789011 

# this defines which permissions you should have (in this case, read-only)
sso_role_name = ReadAccess 
```
Additional information for manually configuring SSO can be found [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-manual). 

Once configured, you can sign-in to your profile by clicking the `AWS: (not connected)` button in the bottom right of VS Code. You should then be directed towards the SSO login page to complete the authorization.

**Comment by JadenSimon** [comment]
If you _just_ need to add a session token (no SSO), you can instead use the following for the credentials file:
```
[default]
aws_access_key_id=[id here]
aws_secret_access_key=[key here]
aws_session_token=[token here]
```

**Comment by justinmk3** [comment]
> the only documentation I can find tells you to [edit the credentials file](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/sso-credentials.html), which doesn't exist yet because the wizard keeps failing

In AWS Toolkit 1.48 (not released yet) ,

1. The `Edit Credentials` command will open (and create) `~/.aws/credentials` file.
2. The `Create Credentials Profile` command was improved so that it validates credentials and you can edit previous steps.

> Add help links to the Credentials related dialogs/wizards

`Create Credentials Profile` shows a help link, which addresses the title of this issue.

The general topic/epic of improving other aspects of credentials (MFA, SSO, ...) is covered in other issues.
