### ISSUE TITLE
The active credentials profile is not used by SAM CLI

### ISSUE THREAD

**Issue by mpiroc** [aws/aws-toolkit-vscode#553]
We do not pass the active credentials profile to `sam deploy`, `sam package`, etc, causing SAM CLI to choose the default credentials profile.

For each SAM CLI command that requires credentials, we should retrieve the active profile name from settings, and include it in the SAM CLI command.

**Comment by bryceitoc9** [comment]
We should also gate the calls if they don't have a profile selected. We can either flash the credential selection prompt or we can error out and tell the user to select a profile themselves.

We should gate because right now we allow deployments even if the user isn't logged in at all; deployments in this state will still deploy to the default profile.
