### ISSUE TITLE
use globalStoragePath to store logs, debugger binaries, etc.

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#582]
`getDefaultLogPath` in `logger.ts` places the logfiles in specific locations.

This causes issues in places like linux, where the `~/.config/Code` folder may not exist. https://code.visualstudio.com/docs/remote/troubleshooting#_errors-storing-extension-data provides guidance to use `context.globalStoragePath`. This became evident when a user tried to use the extension with WSL - see #566 

We should decide if that is a more suitable location for log files to be stored.

**Comment by awschristou** [comment]
Pinging @bryceitoc9  for thoughts.

**Comment by bryceitoc9** [comment]
These are the considerations I took into this path definition:
* The [paths from the extension context](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext) are guaranteed to exist through the parent directory. However, the context is only created if the extension is loaded; our current testing cannot rely on this.
* The logs are not centralized; this makes it more difficult for a user to find the logs and to clean up the AWS logs.
* As far as I could tell at the time, the `<os-specific part>/Code/logs` directory always exists.

Looking back on this, we could probably do a better job of spoofing the extension context (this should(?) ensure that the directory is present). Finding the current logfile shouldn't be too bad either (since we have that configured through a VS Code command). However, the difficulty is in finding older logs and cleaning up existing ones (AFAIK VS Code doesn't do any automatic log cleanup).

**Comment by justinmk3** [comment]
for reference, telemetry module is using `context.globalStoragePath`: https://github.com/aws/aws-toolkit-vscode/blob/47dc2e83f858231f49767ee916c81c0496662220/src/shared/telemetry/defaultTelemetryService.ts#L42

**Comment by justinmk3** [comment]
@JadenSimon https://github.com/aws/aws-toolkit-vscode/pull/1623 suggests also storing debugger binaries in `globalStoragePath`.

**Comment by JadenSimon** [comment]
Our Go and C# lambdas currently store the debugger binary within the project directory. While this works, it would be much better to store them in a centralized location as to not clutter the user's workspace. This comes with the added bonus of being properly disposed of when the extension is removed. There may be some issues with mounting binaries from the `globalStoragePath` that are system dependent; more experimentation needs to be done.

**Comment by justinmk3** [comment]
fixed by https://github.com/aws/aws-toolkit-vscode/pull/1694
