### ISSUE TITLE
ENOENT error when there is a config file but not a credentials file present

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#641]
If shared credentials are set up in the config file, and no credentials file is present, the toolkit brings up an error message when trying to connect to AWS. Users are unable to connect to AWS unless they make an empty credentials file in the `.aws` folder at the very least.

This was demonstrated on OSX

**Comment by rli** [comment]
This also has implications for telemetry publishing
```
Got Failed to get an Cognito identity for telemetry: Error: ENOENT: no such file or directory, open '/Users/<user>/.aws/credentials' while initializing telemetry publisher
defaultTelemetryService.js:163
```

**Comment by bryceitoc9** [comment]
Looks like the error is present but different on Windows: `2020-11-30 12:49:41 [ERROR]: Error trying to connect to AWS with Credentials Provider profile:default. Toolkit will now disconnect from AWS. [TypeError: Cannot redefine property: default`

**Comment by bryceitoc9** [comment]
Appears that this was fixed recently in the JS SDK: https://github.com/aws/aws-sdk-js/issues/3436

**Comment by bryceitoc9** [comment]
Bumped the aws-sdk version to current (2.799.0) and it still doesn't appear that it's working. The last resort would be to create a blank ~/.aws/credentials` file as that resolves the issue.

**Comment by justinmk3** [comment]
Related aws-sdk-js commit: https://github.com/aws/aws-sdk-js/commit/7d4dd548f74f739dbe0df1c4b9cd88454ce5d131

@thomasmichaelwallace can you confirm that that commit should fix the issue described here?

**Comment by thomasmichaelwallace** [comment]
@justinmk3 yes- the fix was designed for the case where you wanted to only use a config file with no credentials. I use it myself in production (on osx and linux).

To help debug, can I invite you to work through the following response to someone else who '@'d me about the fix: https://github.com/aws/aws-sdk-js/issues/3436#issuecomment-727180538

Assuming that this toolkit (which I do not use) isn't doing anything too exciting, I suspect your environment is either not setup correctly, or is not being carried over into vscode.

As a hunch, your debugging may reveal a separate bug that the sdk requires a credential file to resolve the region. But, at present, that's pure speculation on my part.

**Comment by justinmk3** [comment]
Toolkit 1.23 includes https://github.com/aws/aws-toolkit-vscode/pull/1626 which should fix this. This prerelease build includes the fix, we appreciate your feedback:

1. Download and extract 
[aws-toolkit.zip](https://github.com/aws/aws-toolkit-vscode/files/6281457/aws-toolkit.zip)
2. From the VSCode command list (`ctrl-shift-p` or `cmd-shift-p`) run `Extensions: Install from VSIX...` to install the `*.vsix` file.
3. Reload VSCode and verify that the Toolkit has the new version (not the release/older version).
