### ISSUE TITLE
SAM deploy with non-existant template just closes the wizard

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#659]
**To Reproduce**
1. Go to SAM deploy
2. Enter a file that doesn't exist
3. Wizard closes with no error

**Expected behavior**
Should report file not found

**Comment by bryceitoc9** [comment]
The issue here is that this is a VS Code Quick Pick list--the text box is a filter and not a selector, and pressing enter (selecting nothing) backs you out of the wizard.

We need to give the user feedback that they have no templates, either through an info/warning/error message toast or through a quick pick item informing the user of the empty list.

**Comment by justinmk3** [comment]
the new `AWS: Sync SAM Application` command doesn't allow selection of a non-existent template.
