### ISSUE TITLE
Show Lambda ARN in the invoke UI

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-vscode#663]
If you have a Lambda function in two regions with same name, there is no way to tell in the remote invoke UI which one is which.

Specification:
* The Lambda Invoke page shows the lambda resource's ARN
* The Lambda Invoke page shows the lambda resource's region

**Comment by LukvonStrom** [comment]
Hi @abrooksv ,
I would be interested in doing a PR for this years hacktoberfest.
I am proposing the following patch:
- Parsing the region out of the ARN (the aws-sdk provides now region itself in the FunctionConfig, as documented [here](https://github.com/aws/aws-sdk-js/blob/master/clients/lambda.d.ts#L963))
- Adding the region to the return of the functionName Getter of the [lambdaFunctionNode.ts](https://github.com/aws/aws-toolkit-vscode/blob/master/src/lambda/explorer/lambdaFunctionNode.ts#L33) file
- If needed I could also add another getter for the region.

**Comment by awschristou** [comment]
Hi @LukvonStrom we'd be interested in having you contribute! I will assign you this task.

You might not need to parse the ARN, region is [already exposed](https://github.com/aws/aws-toolkit-vscode/blob/master/src/lambda/explorer/lambdaFunctionNode.ts#L16) on the node. I will update the specification on the issue to explicitly show both arn and region.

(CC: @justinmk3 )

**Comment by justinmk3** [comment]
@LukvonStrom Thanks for your interest! My understanding of the original proposal here is:

The current "invoke lambda" UI looks like this:

<img width="735" alt="Screen Shot 2020-09-28 at 9 12 16 AM" src="https://user-images.githubusercontent.com/55561878/94458524-e8461400-016a-11eb-82b4-3a3d11725b12.png">

The proposal suggests a new field that shows the ARN, to make it clear exactly which Lambda is being invoked:

<img width="735" alt="Screen Shot 2020-09-28 at 9 12 16 AM" src="https://user-images.githubusercontent.com/55561878/94458680-1cb9d000-016b-11eb-84ea-bf25f7e5c9c9.png">


Alternatively (your proposal) we could show the region instead of / in addition to the ARN:

<img width="735" alt="Screen Shot 2020-09-28 at 9 12 16 AM" src="https://user-images.githubusercontent.com/55561878/94458804-4e329b80-016b-11eb-847d-076bf14caef6.png">



- `Lambda.FunctionConfiguration` has a `FunctionArn` field. That could be displayed in the [webview template](src/lambda/templates/lambdaTemplates.ts).
- As @awschristou mentioned we may not need to parse anything to also show the region.

**Comment by LukvonStrom** [comment]
Hi @justinmk3 @awschristou,
I implemented both options for now and also chose to implement a copy arn button (function is alreday available via menu, but I thought it might be handy on the page itself too).

Is the following layout ok for you? 
![image](https://user-images.githubusercontent.com/8446619/94591157-f63d8700-0287-11eb-808c-d361dd62dc97.png)

**Comment by justinmk3** [comment]
@LukvonStrom Looks good, send a PR :) 

Preliminary comments:

- Don't need these fields in bold, they are less important than the other fields.
- Remove "Function" prefix
- Capitalize "ARN"

> also chose to implement a copy arn button (function is alreday available via menu, but I thought it might be handy on the page itself too).

What is the use case there? Is the text not already selectable? I would avoid adding a button unless we expect this to be a common task for users, because it sets a precedent. Since screen space is limited, we should only use it for the most common use-cases. 

(This matters especially because we plan to change the layout of this webview so that it is more compact.)

**Comment by LukvonStrom** [comment]
@justinmk3 I will send a PR on October 1st, as Hacktoberfest will begin then :)

I implemented your suggestions:
![image](https://user-images.githubusercontent.com/8446619/94602756-9817a080-0295-11eb-87e5-8300762f5770.png)

If you want me to, I can remove some paddings to make the view more compact?

**Comment by justinmk3** [comment]
> If you want me to, I can remove some paddings to make the view more compact?

To avoid merge conflicts I would avoid that. We have another pending PR that changes the layout/style.

**Comment by justinmk3** [comment]
Toolkit 1.15 was released today, which includes https://github.com/aws/aws-toolkit-vscode/pull/1334
