### ISSUE TITLE
Add Custom Folder selection to the location picker list in Create SAM App wizard

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-vscode#674]
In the "new SAM Application" workflow, User Studies showed there is some confusion on the step where users are asked to select a location for their application.

The flow for selecting a non-workspace folder does not resonate with users, because their chosen folder is not presented back as an option.

Acceptance Criteria:
* After the Folder Selection dialog is used, the user is taken back to the folder selection picker
* the folder chosen in the selection dialog is shown in the folder selection picker, alongside the workspace folder entries, and the "choose different folder" entry
* the custom chosen folder entry has a description mentioning that this folder will be added to the user's VS Code workspace
* if the user returns back to the Folder Selection dialog, the custom folder entry is updated. There is a maximum of one of these entries in the picker list.
* the custom folder entry is retained for the lifetime of the wizard. If the next wizard step returns back to this step (or this step goes back and then re-advances to this step), the custom folder entry is displayed again

**Comment by diablodale** [comment]
Today I experienced similar workflow problems in this extension as it relates to the workspace folder in the New SAM app command.

## Setup

* Windows 10 x64 w/ current updates
* VS Code 1.36.1 with remote development into WSL
* This extension, version 1.0.0
* This extension installed into WSL Ubuntu 18.04

## Repo

1. Create a new empty directory on your computer. For example, "/mnt/repos/sam-app-1"
2. `git init` in this empty directory. This is the desired folder for the upcoming SAM application.
3. In VS Code, press F1 and choose Create new SAM application
4. Prompted for runtime. Choose node10
5. Prompted "Select a workspace folder for your new project". Choose the directory created in step 1.
6. Prompted "Enter a name for your new application". Type "MySamApp1"

## Result

A new folder "/mnt/repos/sam-app-1/MySamApp1" is created. Inside that folder is a ".gitignore" and yet more folders and files.

## Expected

Inside "/mnt/repos/sam-app-1" are created the ".gitignore" and the folders/files.

## Notes

It would be nonsensical to prompt "Select a workspace folder for your new project" and select /mnt/repos. Why? Because in my setup, /mnt/repos contains 71 different git repos across a wide variety of projects that are unrelated. And that is why I created a new dedicated /mnt/repos/sam-app-1 folder and `git init` inside it.

The app name prompted for in the workflow is not material to the project. I just did a full text search of that app name I gave when prompted and this name only appears in arbitrary descriptions and readme text. Therefore, the app name is not even needed in the New SAM App workflow. It is irrelevant.

I suggest the following:

* Reword the prompt "Select a workspace folder for your new project" to be "Select the folder for your new SAM application"
* Continue to prompt for "Enter a name for your new application".
* Do *not* create a directory with that application name.
* Create the .gitignore and other files/folders in the "Select the folder" above
* Continue to put the "name for your new application" in the README.md and the yml description field. It is irrelevant as before, but it is nice to allow someone to copy/paste commands from the README
